apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: typeahead-svc
  labels:
    app: typeahead
spec:
  selector:
    matchLabels:
      app: typeahead
  serviceName: memcached
  replicas: 3
  template:
    metadata:
      labels:
        app: typeahead
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  typeahead
      containers:
      - name: memcached
        image: registry.access.redhat.com/rhosp13/openstack-memcached:13.0-158.1638430264
        imagePullPolicy: Always
        command:
        - memcached
        - -m 64
        - -o
        - modern
        - -v
        ports:
        - name: memcache
          containerPort: 11211
        livenessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            memory: 64Mi
            cpu: 50m